In [11]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [12]:
env = gym.make("FrozenLake-v0")

In [13]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))


In [14]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate =0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [16]:
rewards_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    if episode % 1000 == 0:
        print('epoch :', len(rewards_all_episodes))
    for step in range(max_steps_per_episode): 

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate: # Exploit
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample() # Explore
            
        
        new_state, reward, done, info = env.step(action) # Get new state and reward for action
        
        # Update Q_table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward 
        if done == True: 
            break
    
    # Exploration decay function
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)
    
print(q_table)
print(exploration_rate)

epoch : 0
epoch : 1000
epoch : 2000
epoch : 3000
epoch : 4000
epoch : 5000
epoch : 6000
epoch : 7000
epoch : 8000
epoch : 9000
[[0.53008463 0.49651265 0.49880147 0.48127751]
 [0.40704137 0.29077209 0.32136697 0.47189096]
 [0.40662012 0.4030405  0.3962986  0.45487721]
 [0.25956898 0.39598715 0.29827863 0.44267543]
 [0.55520866 0.37117075 0.26840244 0.32311451]
 [0.         0.         0.         0.        ]
 [0.17208172 0.15710682 0.41536734 0.15936024]
 [0.         0.         0.         0.        ]
 [0.44205711 0.47643621 0.41299303 0.60353738]
 [0.39372986 0.70244506 0.45191555 0.47526986]
 [0.75511526 0.39777382 0.26101322 0.37438445]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.33922827 0.401842   0.79915261 0.45566329]
 [0.67933998 0.88682921 0.7430845  0.7310592 ]
 [0.         0.         0.         0.        ]]
0.010044990898875783


In [9]:
# Visualisation

for episode in range(3):
    state = env.reset()
    done = False
    print(" Episode ", episode + 1,)
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("win")
                time.sleep(3)
            else:
                print("fell through hole")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state
    
env.close()
        

  (Left)
SFFF
FHFH
FFFH
HFFG
fell through hole


In [18]:
sum(rewards_all_episodes)

5191.0

In [ ]:
rewards_all_episodes